services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nativox-postgres
    environment:
      POSTGRES_DB: nativox
      POSTGRES_USER: nativox
      POSTGRES_PASSWORD: nativox123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
