version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nativox-postgres
    environment:
      POSTGRES_DB: nativox
      POSTGRES_USER: nativox
      POSTGRES_PASSWORD: nativox_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nativox -d nativox"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nativox-network

  # AudioSeg Application
  app:
    build: .
    container_name: nativox-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://nativox:nativox_password@postgres:5432/nativox
      SESSION_SECRET: your-super-secret-session-key-change-this-in-production
      PORT: 5000
    volumes:
      - uploads_data:/app/uploads
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/languages"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nativox-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  nativox-network:
    driver: bridge
