version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nativox-postgres
    environment:
      POSTGRES_DB: nativox
      POSTGRES_USER: nativox
      POSTGRES_PASSWORD: nativox123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Shemasts Application (Development Mode)
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: nativox-app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://nativox:nativox123@postgres:5432/nativox
      SESSION_SECRET: dev-session-secret-key
      PORT: 5000
      # Cloud Storage Configuration
      STORAGE_PROVIDER: aws-s3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: us-east-1
    ports:
      - "3000:5000"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local
