version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nativox-postgres-dev
    environment:
      POSTGRES_DB: nativox_dev
      POSTGRES_USER: nativox
      POSTGRES_PASSWORD: nativox_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nativox -d nativox_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nativox-dev-network

  # Shemasts Application (Development)
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: nativox-app-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://nativox:nativox_password@postgres:5432/nativox_dev
      SESSION_SECRET: dev-session-secret-key
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_dev_data:/app/uploads
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nativox-dev-network
    restart: unless-stopped
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local
  uploads_dev_data:
    driver: local

networks:
  nativox-dev-network:
    driver: bridge
